// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1, arg2, arg3) {
  return window['go']['main']['App']['Execute'](arg1, arg2, arg3);
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function LoadFile() {
  return window['go']['main']['App']['LoadFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}
