// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Execute(arg1:string,arg2:string,arg3:string):Promise<main.Response>;

export function GetFilePath():Promise<string>;

export function LoadFile():Promise<string>;

export function SaveFile(arg1:string):Promise<void>;
